#!/usr/bin/python3
"""
Реализовано перемещение по координатной плоскости.
Вводится наименование команды, после каждого действия
выводится результат работы программы.
"""
print("Enter the command (left, right, up, down) or stop-word (stop): ")
i=input();
x=y=0
while (i != "stop"):
    if (i == "left"):
        x-=1
    elif (i == "right"):
        x+=1
    elif (i == "up"):
        y+=1
    elif (i == "down"):
        y-=1
    else:
        print("Wrong comand!")
    print(f'({x};{y})')
    i=input()
