#!/usr/bin/python3
"""
Содается словарь цвет: rgb пресдавление (ключ: значение). 
Выводится содержимое созданного словаря.
"""
from PIL import ImageColor
list1=["red", "orange", "yellow", "green", "blue", "purple"]
list2=["#ff0000", "#ff8c00", "#ffff00", "#00ff00", "#0000ff", "#800080"]
map={}
for i in list1:
    map[i]=ImageColor.getcolor(list2[list1.index(i)], "RGB")
print(map.items())
