#!/usr/bin/python3
"""
Программа заполняет два множества случайным набором чисел и производит
сравнение.
"""

import random
a=set()
b=set()
for i in range(5):
    a.add(random.randint(0, 9))
for i in range(5):
    b.add(random.randint(0, 9))
print(a)
print(b)
print("Пересечение двух множеств: ", a.intersection(b))
print("Элементы входят в первое множество, во второе нет: ", a.difference(b))
print("Элементы входят во второе множество, в первое нет: ", b.difference(a))
print("Элементы входят в одно из двух множеств: ", a.symmetric_difference(b))
