#!/usr/bin/python3

def fibonachi(num):
    """
    Реализвует подсчет числа Фибоначчи.
    num - номер числва.
    Функция для ряда, начинающегося с двух единиц.
    """
    if num in [1, 2]:
        return 1
    return fibonachi(num-1)+fibonachi(num-2)
        

def fibonachii(num):
    """
    Реализвует подсчет числа Фибоначчи.
    num - номер числва.
    Функция для ряда, начинающегося с нуля.
    """
    if num == 1:
        return 0
    if num in [2, 3]:
        return 1
    return fibonachii(num-1)+fibonachii(num-2)
    
    
print(f'Ряд начинается с единиц (num = 10): {fibonachi(10)}')
print(f'Ряд начинается с нуля (num = 10): {fibonachii(10)}')
