#!/usr/bin/python3
def func(str):
    """
    Функция определяет, соответствует ли пароль критериям ниже:
        Пароль должен содержать не менее 6 символов.
        Пароль не должен состоять только из цифр.
        Пароль не должен содержать слово \"password\" в любом регистре.
        Пароль должен содержать хотя бы одну цифру.
    str - введенный пароль.
    """
    if (len(str) >= 6) and
       (str.isdigit() != True) and
       (str.lower().find("password") == -1) and
       (str.isalpha() != True):
        return True
    return False


print(func(input("Введите пароль: ")))





"""
    assert len(str) >= 6, "Пароль должен содержать не менее 6 символов"
    assert str.isdigit() != True, "Пароль не должен состоять только из цифр"
    assert str.lower().find("password") == -1, "Пароль не должен содержать слово \"password\" в любом регистре"
    assert any(s.isdigit() for s in str) != False, "Пароль должен содержать хотя бы одну цифру" #можно было использовать str.isalpha() != True
"""
